config/routes.rb
Rails.application.routes.draw do
  root 'pets#index'
  get 'login', to: 'users#login'
  post 'logout', to: 'users#logout'
  post 'authenticate', to: 'users#authenticate'

  get 'vet_registration/:id', to: 'vet_registrations#new', as: 'new_pet_vet_registration'
  get 'appointment/pet/:id/appointment/:vet_id', to: 'appointments#new', as: 'new_pet_vet_appointment'

  get 'vet/:id/pets', to: 'vets#index', as: 'vet_pets'
  get 'vet/pets/:id', to: 'vets#show', as: 'vet_pet'
  resources :users
  resources :pets
  resources :vet_registrations
  resources :appointments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :user
  has_many :vet_registrations, dependent: :destroy
  has_many :appointments, dependent: :destroy
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  def index
    @headers = { "Content-Type" => "application/json", "Authorization" => cookies[:Authorization]}
    @pets = HTTParty.get('http://localhost:3000/pets', headers: @headers)
    #@pets["auth_token"] = cookies[:Authorization]
  end

  def show
    @headers = { 
      "Content-Type" => "application/json",
      "Authorization" => cookies[:Authorization]
    }
    @pet = HTTParty.get('http://localhost:3000/pets/'+ params[:id], headers: @headers)
    @vet_registrations = HTTParty.get('http://localhost:3000/vet_registrations/', headers: @headers)
    @vets = @vet_registrations.select { |vet| vet["pet_id"] == params[:id].to_i } 

    @doctors = HTTParty.get('http://localhost:3000/users/', headers: @headers)
    @appointments = HTTParty.get('http://localhost:3000/appointments', headers: @headers)
  

  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    @headers = { 
      "Content-Type" => "application/json",
      "Authorization" => cookies[:Authorization]
    }
    @body = {
      name: @pet.name,
      pet_type: @pet.pet_type
    }.to_json
    @response = HTTParty.post('http://localhost:3000/pets',  body: @body, headers: @headers)

    redirect_to root_path
  end

  def edit
    @headers = { 
      "Content-Type" => "application/json",
      "Authorization" => cookies[:Authorization]
    }
    @response = HTTParty.get('http://localhost:3000/pets/'+ params[:id], headers: @headers)

    @pet = Pet.new
    @pet.id = @response['id']
    @pet.name = @response['name']
    @pet.pet_type = @response['pet_type']
    @pet.user_id = @response['user_id']
    @pet.created_at = @response['created_at']
    @pet.updated_at = @response['updated_at']
    
  end

  def update
    @headers = { 
      "Content-Type" => "application/json",
      "Authorization" => cookies[:Authorization]
    }
    @pet_name = params[:pet][:name]
    @pet_type = params[:pet][:pet_type] 
    
    @body = {
      name: @pet_name,
      pet_type: @pet_type
  }.to_json
 
    @response = HTTParty.patch('http://localhost:3000/pets/' + params[:id], body:@body, headers: @headers)
    redirect_to root_path
  end

  def destroy
    @headers = { 
      "Content-Type" => "application/json",
      "Authorization" => cookies[:Authorization]
    }
    @response = HTTParty.delete('http://localhost:3000/pets/' + params[:id], headers: @headers)
 
    redirect_back(fallback_location: root_path)
  end

  private
  def pet_params
    params.require(:pet).permit(:name, :pet_type)
  end

end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/pets/_form.html.erb
<%= form_with model:@pet, local:true do |form| %>
 
  <% if @pet.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@pet.errors.count, "error") %> prohibited
        this pet from being saved:
      </h2>
      <ul>
        <% @pet.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name, class: 'form-control col-md-6' %>
  </p>
 
  <p>
    <%= form.label :pet_type %><br>
    <%= form.text_field :pet_type, class: 'form-control col-md-6' %>
  </p>
 
  <p>
    <%= form.submit class: 'btn btn-md btn-outline-success'%> | <%= link_to "Back", pets_path, class: 'btn btn-md btn-outline-info' %>
  </p>
 
<% end %>

app/views/pets/edit.html.erb
<%= form_for @pet, url:{action: "update"}, method: :patch, local:true do |form| %>
 
  <% if @pet.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@pet.errors.count, "error") %> prohibited
        this pet from being saved:
      </h2>
      <ul>
        <% @pet.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name, class: 'form-control col-md-6' %>
  </p>
 
  <p>
    <%= form.label :pet_type %><br>
    <%= form.text_field :pet_type, class: 'form-control col-md-6' %>
  </p>
 
  <p>
    <%= form.submit class: 'btn btn-md btn-outline-success'%> | <%= link_to "Back", pets_path, class: 'btn btn-md btn-outline-info'%>
  </p>
 
<% end %>

app/views/pets/index.html.erb
<div class="jumbotron jumbotron-fluid mt-5">
  <div class="container">
    <h1 class="display-4">Pets List</h1>
    <p class="lead"></p>
  </div>
</div>


<%= link_to 'Create New Pet', new_pet_path, class: 'btn btn-outline-success'%>

<% if @pets.present? %>
<table class="table mt-5">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Pet Type</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
  <% @pets.each do |pet| %>
    <tr>
      <td><%= pet["name"]%></td>
      <td><%= pet["pet_type"]%></td>
      <td><%= link_to 'Show', pet_path(pet["id"]), class: 'btn btn-sm btn-outline-info' %> | <%= link_to 'Edit', edit_pet_path(pet["id"]), class: 'btn btn-sm btn-outline-warning text-warning' %> | <%= link_to 'Destroy', pet_path(pet["id"]), class:'btn btn-sm btn-outline-danger', method: :delete, data: {confirm: "Are you sure you want to delete this pet?"} %> </td>
    </tr>
  <% end %>  
    
  </tbody>
</table>

<% else %>

<h1 class="mt-4">Pets List Empty</h1>

<% end %>

app/views/pets/new.html.erb
<div class="jumbotron jumbotron-fluid mt-5">
  <div class="container">
    <h1 class="display-4">Add New Pet</h1>
    <p class="lead"></p>
  </div>
</div>

<%= render 'form' %>

app/views/pets/show.html.erb
<div class="jumbotron jumbotron-fluid mt-5">
  <div class="container">
    <h1 class="display-4"> <%= @pet["name"] %> - <%= @pet["pet_type"] %> </h1>
    <p class="lead"></p>

    <% if @vets.present? %>
    <table class="table mt-5">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Vet</th>
      <th scope="col">Email</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>

  <% @vets.each do |vet| %>
    <tr>
      <td><%= @doctors.select {|name| name["id"] == vet["vet_id"] }.map { |name| name["name"] }.first %></td>
      <td><%= @doctors.select {|name| name["id"] == vet["vet_id"] }.map { |name| name["email"] }.first %></td>
      <td><%= link_to 'Remove Vet', vet_registration_path(vet["id"]), class:'btn btn-sm btn-outline-danger', method: :delete, data: {confirm: "Are you sure you want to delete this vet?"} %> | <%= link_to "Book Appointment", new_pet_vet_appointment_path(params[:id],vet["vet_id"]), class:"btn btn-sm btn-outline-warning" %> </td>
    </tr>
  <% end%>
    
  </tbody>
</table>
<% else %>
<h2>Not registered to any vet</h2>
<% end %>
  </div>
</div>

<% if @vets.present? %>
<div class="mt-3">
  <%= link_to "Back To Pets List", pets_path, class:"btn btn-md btn-outline-info" %>
</div>

<% else %>
<div class="mt-3">
  <%= link_to "Register Vet", new_pet_vet_registration_path(params[:id]), class:"btn btn-md btn-outline-success" %> | <%= link_to "Back To Pets List", pets_path, class:"btn btn-md btn-outline-info" %>
</div>

<% end %>

<% if @appointments.present? %>
<h3 class="mt-5">Vet Appointments</h3>

<table class="table mt-5">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Date</th>
      <th></th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>

    <% @appointments.select {|appointment| appointment["pet_id"] == params[:id].to_i }.each do |app| %>
    <tr>
      <td><%= app["date"] %></td>
      <td><%= link_to 'Cancel Appointment', appointment_path(app["id"]), class:'btn btn-sm btn-outline-danger', method: :delete, data: {confirm: "Are you sure you want to delete this appointment?"} %></td>
    </tr>
  <% end%>
    
  </tbody>
</table>

<% end %>