config/routes.rb
Rails.application.routes.draw do
  root 'pets#index'
  get 'login', to: 'users#login'
  post 'logout', to: 'users#logout'
  post 'authenticate', to: 'users#authenticate'

  get 'vet_registration/:id', to: 'vet_registrations#new', as: 'new_pet_vet_registration'
  get 'appointment/pet/:id/appointment/:vet_id', to: 'appointments#new', as: 'new_pet_vet_appointment'

  get 'vet/:id/pets', to: 'vets#index', as: 'vet_pets'
  get 'vet/pets/:id', to: 'vets#show', as: 'vet_pet'
  resources :users
  resources :pets
  resources :vet_registrations
  resources :appointments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/vets_controller.rb
class VetsController < ApplicationController
  def index
    @headers = { "Content-Type" => "application/json", "Authorization" => cookies[:Authorization]}
    @vet_registrations = HTTParty.get('http://localhost:3000/vet_index', headers: @headers)
    @pets = @vet_registrations.select { |pet| pet["vet_id"] == params[:id].to_i }

    @pet_names = HTTParty.get('http://localhost:3000/vet_pets_index', headers: @headers)
    @pet_name = @pet_names.select { |pet| pet["pet_id"] == params[:id].to_i }


    @owner = HTTParty.get('http://localhost:3000/users', headers: @headers)
  end

  def show
    @headers = { 
      "Content-Type" => "application/json",
      "Authorization" => cookies[:Authorization]
    }
    @vet_pet = HTTParty.get('http://localhost:3000/pets/'+ params[:id], headers: @headers)
    @appointments = HTTParty.get('http://localhost:3000/vet_appointments_index', headers: @headers)

  end
end

app/views/vets/index.html.erb
<div class="jumbotron jumbotron-fluid mt-5">
  <div class="container">
    <h1 class="display-4">Pets Registered</h1>
    <p class="lead"></p>
  </div>
</div>
<table class="table mt-5">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Pet Name</th>
      <th scope="col">Pet Type</th>
      <th>Owner</th>
      <th>Email</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>

    <% @pets.each do |pet| %>
    <tr>
      <td><%= @pet_names.select { |pet_name| pet_name["id"] == pet["pet_id"].to_i }.map {|name| name["name"]}.first %></td>
      <td><%= @pet_names.select { |pet_name| pet_name["id"] == pet["pet_id"].to_i }.map {|name| name["pet_type"]}.first %></td>
      <td><%= @owner.select { |owner| owner["id"] == pet["user_id"].to_i }.map {|name| name["name"]}.first %></td>
      <td><%= @owner.select { |owner| owner["id"] == pet["user_id"].to_i }.map {|name| name["email"]}.first %></td>
      <td><%= link_to 'View Pet Details', vet_pet_path(@pet_names.select { |pet_name| pet_name["id"] == pet["pet_id"].to_i }.map {|name| name["id"]}.first), class: 'btn btn-sm btn-outline-info' %></td>
    </tr>
  <% end%>
    
  </tbody>
</table>

app/views/vets/show.html.erb
<div class="jumbotron jumbotron-fluid mt-5">
  <div class="container">
    <h1 class="display-4"> <%= @vet_pet["name"] %> - <%= @vet_pet["pet_type"] %> </h1>
    <p class="lead"></p>

  </div>
</div>


<% if @appointments.present? %>
<h3 class="mt-5">Vet Appointments</h3>

<table class="table mt-5">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Date</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>

    <% @appointments.select {|appointment| appointment["pet_id"] == params[:id].to_i }.each do |app| %>
    <tr>
      <td><%= app["date"] %></td>
    </tr>
  <% end%>
    
  </tbody>
</table>

<% end %>

<%= link_to 'Back', :back, class: 'btn btn-outline-warning' %>