config/routes.rb
Rails.application.routes.draw do
  root 'pets#index'
  get 'login', to: 'users#login'
  post 'logout', to: 'users#logout'
  post 'authenticate', to: 'users#authenticate'

  get 'vet_registration/:id', to: 'vet_registrations#new', as: 'new_pet_vet_registration'
  get 'appointment/pet/:id/appointment/:vet_id', to: 'appointments#new', as: 'new_pet_vet_appointment'

  get 'vet/:id/pets', to: 'vets#index', as: 'vet_pets'
  get 'vet/pets/:id', to: 'vets#show', as: 'vet_pet'
  resources :users
  resources :pets
  resources :vet_registrations
  resources :appointments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :pets, dependent: :destroy
  has_many :appointments, dependent: :destroy
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @headers = { 
      "Content-Type" => "application/json",
      "Authorization" => cookies[:Authorization]
    }
    @users = HTTParty.get('http://localhost:3000/users', headers: @headers)
  end

  def show 
  end

  def new
    @user = User.new
  end
 
  def create 
   
    @body = User.new(user_params)
    @headers = { "Content-Type" => "application/json"}
    @body_hash = {
      name: @body.name,
      email: @body.email,
      password: @body.password,
      password_confirmation: @body.password_confirmation,
      role: @body.role

    }.to_json

    @post_user = HTTParty.post('http://localhost:3000/signup', body: @body_hash, headers: @headers)
    cookies[:Authorization] = @post_user["auth_token"]

    @headers = { "Content-Type" => "application/json", "Authorization" => cookies[:Authorization]}
    @users = HTTParty.get('http://localhost:3000/users', headers: @headers)

    if @body.role == "vet"
      @users = HTTParty.get('http://localhost:3000/users', headers: @headers)
      @user = @users.select { |user| user["email"] == @body.email }.first
      redirect_to vet_pets_path(@user["id"])
    else 
      redirect_to root_path
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end


  def login
    @user = User.new  
  end

  def authenticate
    @body = User.new(user_params)
    @headers = { "Content-Type" => "application/json"}
    @body_hash = {
      email: @body.email,
      password: @body.password,
    }.to_json
    
    @login_user = HTTParty.post('http://localhost:3000/auth/login', body: @body_hash, headers: @headers)

    if @login_user.response.body["auth_token"].present?

      cookies[:Authorization] = @login_user["auth_token"]

      @users = HTTParty.get('http://localhost:3000/users', headers: @headers)
      @user = @users.select { |user| user["email"] == @body['email'] }.first
      
      if @user["role"] == "vet"
        redirect_to vet_pets_path(@user["id"]) 
      elsif @user["role"] == "owner"
        redirect_to root_path
      else 
        redirect_to login_path
      end
    end
  end

  def logout
    @headers = { 
      "Content-Type" => "application/json",
      "Authorization" => cookies[:Authorization]
    }

    cookies[:Authorization] = ""
    redirect_to login_path
  end


  private
  def user_params
    params.require(:user).permit(:name, :email, :role, :password, :password_confirmation)
  end

  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with model:@user, local:true do |form| %>
 
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited
        this user from being saved:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name, class: 'form-control col-md-6' %>
  </p>
 
  <p>
    <%= form.label :email %><br>
    <%= form.text_field :email, class: 'form-control col-md-6' %>
  </p>

   <p>
    <%= form.label :role %><br>
    <%= form.select :role, [['vet', 'vet'], ['owner', 'owner']], class: 'form-control col-md-6' %>
  </p>

   <p>
    <%= form.label :password %><br>
    <%= form.password_field :password, class: 'form-control col-md-6' %>
  </p>

  <p>
    <%= form.label :password_confirmtion %><br>
    <%= form.password_field :password_confirmation, class: 'form-control col-md-6' %>
  </p>

   
 
  <p>
    <%= form.submit class: 'btn btn-outline-success' %> | <%= link_to 'Back', users_path ,class: 'btn btn-outline-info'%> 
  </p>
 
<% end %>

app/views/users/index.html.erb
<div class="jumbotron jumbotron-fluid mt-5">
  <div class="container">
    <h1 class="display-4">Users List</h1>
    <p class="lead"></p>
  </div>
</div>

<%= link_to 'Create New User', new_user_path, class: 'btn btn-outline-success'%>

<table class="table mt-5">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Role</th>
    </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= user["name"]%></td>
      <td><%= user["email"]%></td>
      <td><%= user["role"]%></td>
    </tr>
    <% end %>
  
  </tbody>
</table>

app/views/users/login.html.erb
<div class="mt-5">
<%= form_with model:@user, url: authenticate_path, local:true do |form| %>
 
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited
        this user from being saved:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 

  <p>
    <%= form.label :email %><br>
    <%= form.text_field :email, class: 'form-control col-md-6' %>
  </p>

   <p>
    <%= form.label :password %><br>
    <%= form.password_field :password, class: 'form-control col-md-6' %>
  </p>

  <p>
    <%= form.submit "Login", class: 'btn btn-outline-success' %> | <%= link_to 'Back', users_path ,class: 'btn btn-outline-info'%> 
  </p>
 
<% end %>
</div>

app/views/users/new.html.erb
<div class="jumbotron jumbotron-fluid mt-5">
  <div class="container">
    <h1 class="display-4">Add New User</h1>
    <p class="lead"></p>
  </div>
</div>

<%= render 'form' %>

app/views/users/show.html.erb
<div class="jumbotron jumbotron-fluid mt-5">
  <div class="container">
    <h1 class="display-4">Users Details</h1>
    <p class="lead"></p>
  </div>
</div>