config/routes.rb
Rails.application.routes.draw do
  root 'pets#index'
  get 'login', to: 'users#login'
  post 'logout', to: 'users#logout'
  post 'authenticate', to: 'users#authenticate'

  get 'vet_registration/:id', to: 'vet_registrations#new', as: 'new_pet_vet_registration'
  get 'appointment/pet/:id/appointment/:vet_id', to: 'appointments#new', as: 'new_pet_vet_appointment'

  get 'vet/:id/pets', to: 'vets#index', as: 'vet_pets'
  get 'vet/pets/:id', to: 'vets#show', as: 'vet_pet'
  resources :users
  resources :pets
  resources :vet_registrations
  resources :appointments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VetappConsumer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">

  </head>

  <body>
    <div class="container mb-5">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">VetApp</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
      <% if cookies[:Authorization].present? %>

        <%= link_to 'Logout', logout_path, class: 'nav-item nav-link', method: :post, data: {confirm: 'Are you sure you want to logout?'}  %>
        <% else %>
        <%= link_to 'Login', login_path, class: 'nav-item nav-link' %>
        <%= link_to 'Create User', new_user_path, class: 'nav-item nav-link' %>

        <% end %>
      </div>
    </div>
    </nav>
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>

  </body>
</html>